#!/bin/bash
export SPOTIFY_USER_ID="${SPOTIFY_USER_ID}"
export SPOTIFY_CLIENT_ID="${SPOTIFY_CLIENT_ID}"
export SPOTIFY_CLIENT_SECRET="${SPOTIFY_CLIENT_SECRET}"
export SPOTIFY_REDIRECT_URI="${SPOTIFY_REDIRECT_URI}"

exec "$@"